
import React, { useState } from 'react';
import { MarketingStudioProject } from '../types';
import { generateMarketingAnalysis } from '../services/geminiService';
import Button from './ui/Button';
import { BrandLogo } from './ui/BrandLogo';

const MarketingIcon = () => (
    <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
    </svg>
);

const CopyIcon = () => <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 mr-1.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 002 2h10a2 2 0 002-2v-2" /></svg>;
const DownloadIcon = () => <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 mr-1.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>;
const CheckIcon = () => <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 mr-1.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg>;


const MarketingStudio: React.FC<{
    project: MarketingStudioProject;
    setProject: React.Dispatch<React.SetStateAction<MarketingStudioProject>>;
}> = ({ project, setProject }) => {

    const [copied, setCopied] = useState(false);

    const onGenerate = async () => {
        if (project.brandType === 'new' && (!project.brandName || !project.specialty)) {
            setProject(s => ({ ...s, error: 'Please enter brand name and specialty' }));
            return;
        }
        if (project.brandType === 'existing' && !project.websiteLink) {
            setProject(s => ({ ...s, error: 'Please enter a website link' }));
            return;
        }

        setProject(s => ({ ...s, isGenerating: true, error: null, result: null }));
        try {
            const data = project.brandType === 'new' 
                ? { type: project.brandType, name: project.brandName, specialty: project.specialty, brief: project.brief }
                : { type: project.brandType, link: project.websiteLink };
            
            const strategy = await generateMarketingAnalysis(data as any, project.language);
            setProject(s => ({ ...s, result: strategy, isGenerating: false }));
        } catch (err) {
            setProject(s => ({ ...s, isGenerating: false, error: 'Strategy generation failed. Please try again.' }));
        }
    };

    const handleCopy = () => {
        if (!project.result) return;
        navigator.clipboard.writeText(project.result);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleDownload = (format: 'txt' | 'md' | 'pdf') => {
        if (!project.result) return;
        
        if (format === 'pdf') {
            const printWindow = window.open('', '_blank');
            if (!printWindow) return;
            printWindow.document.write(`
                <html>
                <head>
                    <title>SMART Studio Marketing Report - ${project.brandName || 'Analysis'}</title>
                    <link href="https://fonts.googleapis.com/css2?family=Tajawal:wght@400;700&display=swap" rel="stylesheet">
                    <style>
                        body { font-family: 'Tajawal', sans-serif; direction: ${project.language === 'ar' ? 'rtl' : 'ltr'}; padding: 40px; line-height: 1.6; }
                        h1, h2, h3 { color: #ff0000; border-bottom: 2px solid #eee; padding-bottom: 10px; }
                        p { font-size: 14px; color: #333; }
                        .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #666; border-top: 1px solid #eee; padding-top: 20px; }
                    </style>
                </head>
                <body>
                    <div style="text-align: center; margin-bottom: 40px;">
                        <h1 style="margin: 0;">AI Marketing Strategy Report</h1>
                        <p>Generated by SMART Studio PRO</p>
                    </div>
                    <div style="white-space: pre-wrap;">${project.result}</div>
                    <div class="footer">Confidential Report &copy; ${new Date().getFullYear()} SMART Studio</div>
                    <script>window.onload = () => { window.print(); }</script>
                </body>
                </html>
            `);
            printWindow.document.close();
            return;
        }

        const element = document.createElement("a");
        const file = new Blob([project.result], { type: 'text/plain' });
        element.href = URL.createObjectURL(file);
        element.download = `SMART-Studio-Marketing-Strategy.${format}`;
        document.body.appendChild(element);
        element.click();
        document.body.removeChild(element);
    };

    return (
        <main className="w-full flex flex-col gap-8 pt-4 pb-12 animate-in fade-in duration-700">
            {/* Control Center */}
            <div className="glass-card rounded-[2.5rem] p-8 shadow-2xl border border-white/5">
                <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4">
                    <h2 className="text-3xl font-black text-white tracking-tighter flex items-center">
                        <MarketingIcon /> STRATEGIC MARKETING ENGINE
                    </h2>
                    <div className="flex bg-black/40 rounded-full p-1 border border-white/10">
                        <button 
                            onClick={() => setProject(s => ({ ...s, language: 'ar' }))}
                            className={`px-6 py-2 rounded-full text-[10px] font-black uppercase tracking-widest transition-all ${project.language === 'ar' ? 'bg-[var(--color-accent)] text-white shadow-lg' : 'text-white/40 hover:text-white/60'}`}
                        >
                            Arabic
                        </button>
                        <button 
                            onClick={() => setProject(s => ({ ...s, language: 'en' }))}
                            className={`px-6 py-2 rounded-full text-[10px] font-black uppercase tracking-widest transition-all ${project.language === 'en' ? 'bg-[var(--color-accent)] text-white shadow-lg' : 'text-white/40 hover:text-white/60'}`}
                        >
                            English
                        </button>
                    </div>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-12 gap-10">
                    {/* Left: Input Selection */}
                    <div className="lg:col-span-5 space-y-6">
                        <div className="flex p-1 bg-black/20 rounded-2xl border border-white/5">
                            <button 
                                onClick={() => setProject(s => ({ ...s, brandType: 'new' }))}
                                className={`flex-1 py-3 rounded-xl text-xs font-bold transition-all ${project.brandType === 'new' ? 'bg-white/10 text-white shadow-inner' : 'text-white/30 hover:text-white/50'}`}
                            >
                                New Brand Concept
                            </button>
                            <button 
                                onClick={() => setProject(s => ({ ...s, brandType: 'existing' }))}
                                className={`flex-1 py-3 rounded-xl text-xs font-bold transition-all ${project.brandType === 'existing' ? 'bg-white/10 text-white shadow-inner' : 'text-white/30 hover:text-white/50'}`}
                            >
                                Existing Brand (Link)
                            </button>
                        </div>

                        {project.brandType === 'new' ? (
                            <div className="space-y-4 animate-in slide-in-from-left-4 duration-500">
                                <div className="space-y-1.5">
                                    <label className="text-[10px] font-black text-white/40 uppercase tracking-[0.2em] ml-1">Brand Name</label>
                                    <input 
                                        value={project.brandName}
                                        onChange={e => setProject(s => ({ ...s, brandName: e.target.value }))}
                                        placeholder="e.g. 'Volt Energy'"
                                        className="w-full bg-white/5 border border-white/10 rounded-2xl p-4 text-sm font-bold text-white focus:border-[var(--color-accent)]/50 focus:ring-0 outline-none"
                                    />
                                </div>
                                <div className="space-y-1.5">
                                    <label className="text-[10px] font-black text-white/40 uppercase tracking-[0.2em] ml-1">Specialty / Industry</label>
                                    <input 
                                        value={project.specialty}
                                        onChange={e => setProject(s => ({ ...s, specialty: e.target.value }))}
                                        placeholder="e.g. 'Natural Energy Drinks'"
                                        className="w-full bg-white/5 border border-white/10 rounded-2xl p-4 text-sm font-bold text-white focus:border-[var(--color-accent)]/50 focus:ring-0 outline-none"
                                    />
                                </div>
                                <div className="space-y-1.5">
                                    <label className="text-[10px] font-black text-white/40 uppercase tracking-[0.2em] ml-1">Project Brief (Optional)</label>
                                    <textarea 
                                        value={project.brief}
                                        onChange={e => setProject(s => ({ ...s, brief: e.target.value }))}
                                        rows={4}
                                        placeholder="Describe your vision, target audience, or specific goals..."
                                        className="w-full bg-white/5 border border-white/10 rounded-2xl p-4 text-sm font-bold text-white focus:border-[var(--color-accent)]/50 focus:ring-0 outline-none resize-none suggestions-scrollbar"
                                    />
                                </div>
                            </div>
                        ) : (
                            <div className="space-y-4 animate-in slide-in-from-left-4 duration-500">
                                <div className="space-y-1.5">
                                    <label className="text-[10px] font-black text-white/40 uppercase tracking-[0.2em] ml-1">Website or Store Link</label>
                                    <input 
                                        value={project.websiteLink}
                                        onChange={e => setProject(s => ({ ...s, websiteLink: e.target.value }))}
                                        placeholder="https://yourbrand.com"
                                        className="w-full bg-white/5 border border-white/10 rounded-2xl p-4 text-sm font-bold text-white focus:border-[var(--color-accent)]/50 focus:ring-0 outline-none"
                                    />
                                </div>
                                <div className="bg-blue-500/5 border border-blue-500/20 rounded-2xl p-5">
                                    <p className="text-[11px] text-blue-400 font-medium leading-relaxed italic">
                                        💡 AI will use Google Search to analyze this website, identify competitors, and evaluate current market positioning.
                                    </p>
                                </div>
                            </div>
                        )}

                        <Button
                            onClick={onGenerate}
                            disabled={project.isGenerating}
                            loading={project.isGenerating}
                            fullWidth
                            variant="primary"
                            className="font-black py-5 shadow-xl uppercase tracking-widest"
                        >
                            {project.isGenerating ? 'ANALYZING MARKET...' : 'Generate AI Strategy'}
                        </Button>
                    </div>

                    {/* Right: Mapped Features List */}
                    <div className="lg:col-span-7 flex flex-col gap-4">
                        <h4 className="text-[10px] font-black text-white/30 uppercase tracking-[0.2em] ml-1">What this analysis covers:</h4>
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                            {[
                                { t: 'Professional SWOT', d: 'Comprehensive risk & growth map' },
                                { t: 'Real Persona', d: 'Based on actual buying behaviors' },
                                { t: 'Competitor Gaps', d: 'Fnding where others fail' },
                                { t: 'Value Proposition', d: 'Crafting a selling USP' },
                                { t: 'GTM Strategy', d: 'Step-by-step launch plan' },
                                { t: 'Pricing Logic', d: 'Smart market-fit pricing' },
                                { t: '30-60-90 Roadmap', d: 'Actionable execution timeline' },
                                { t: 'KPI Dashboard', d: 'Growth metrics to track' }
                            ].map((item, i) => (
                                <div key={i} className="bg-white/5 border border-white/5 rounded-2xl p-4 flex flex-col gap-1 group hover:border-[var(--color-accent)]/20 transition-all">
                                    <span className="text-xs font-bold text-white group-hover:text-[var(--color-accent)] transition-colors">{item.t}</span>
                                    <span className="text-[10px] text-white/30 font-medium">{item.d}</span>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            </div>

            {/* Result Area */}
            {project.result && (
                <div className="animate-in slide-in-from-bottom-8 fade-in duration-1000 space-y-6">
                    <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                        <h3 className="text-xl font-black text-white uppercase tracking-widest flex items-center gap-2.5">
                            <div className="w-2 h-2 bg-emerald-500 rounded-full animate-pulse"></div> Strategic Intelligence Report
                        </h3>
                        <div className="flex gap-2 flex-wrap">
                            <button onClick={handleCopy} className="px-5 py-2 bg-white/5 hover:bg-white/10 text-white rounded-full text-[10px] font-black uppercase tracking-widest flex items-center transition-all">
                                {copied ? <CheckIcon /> : <CopyIcon />} {copied ? 'Copied' : 'Copy Text'}
                            </button>
                            <button onClick={() => handleDownload('pdf')} className="px-5 py-2 bg-[var(--color-accent)] hover:bg-[var(--color-accent-dark)] text-white rounded-full text-[10px] font-black uppercase tracking-widest flex items-center transition-all shadow-lg shadow-[var(--color-accent)]/20">
                                <DownloadIcon /> Print / PDF
                            </button>
                            <div className="h-8 w-px bg-white/10 mx-1"></div>
                            <button onClick={() => handleDownload('md')} className="px-5 py-2 bg-white/5 hover:bg-white/10 text-white rounded-full text-[10px] font-black uppercase tracking-widest flex items-center transition-all">.MD</button>
                            <button onClick={() => handleDownload('txt')} className="px-5 py-2 bg-white/5 hover:bg-white/10 text-white rounded-full text-[10px] font-black uppercase tracking-widest flex items-center transition-all">.TXT</button>
                        </div>
                    </div>

                    <div className="glass-card rounded-[2.5rem] p-8 md:p-12 shadow-inner border border-white/5 relative bg-white/[0.01]">
                        <div 
                            className={`prose prose-invert max-w-none text-white/80 font-medium leading-relaxed suggestions-scrollbar overflow-y-auto max-h-[1200px] ${project.language === 'ar' ? 'text-right' : 'text-left'}`} 
                            style={{ direction: project.language === 'ar' ? 'rtl' : 'ltr' }}
                        >
                            {project.result.split('\n').map((line, i) => {
                                if (line.startsWith('# ')) return <h1 key={i} className="text-3xl font-black text-white mt-10 mb-6 border-b-2 border-white/5 pb-4 uppercase tracking-tighter">{line.replace('# ', '')}</h1>;
                                if (line.startsWith('## ')) return <h2 key={i} className="text-2xl font-bold text-[var(--color-accent)] mt-12 mb-4 uppercase tracking-tight">{line.replace('## ', '')}</h2>;
                                if (line.startsWith('### ')) return <h3 key={i} className="text-lg font-black text-white/90 mt-8 mb-3 uppercase tracking-widest flex items-center gap-2"><div className="w-1 h-4 bg-[var(--color-accent)]"></div> {line.replace('### ', '')}</h3>;
                                if (line.trim() === '') return <div key={i} className="h-4"></div>;
                                return <p key={i} className="mb-4 text-white/70">{line}</p>;
                            })}
                        </div>
                        
                        {/* Decorative Background Branding */}
                        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 opacity-[0.02] pointer-events-none select-none">
                            <BrandLogo size="lg" className="w-[500px]" />
                        </div>
                    </div>
                </div>
            )}

            {project.error && (
                <div className="bg-red-500/10 border border-red-500/20 text-red-400 p-6 rounded-[2rem] text-sm text-center font-bold animate-shake">
                    {project.error}
                </div>
            )}
        </main>
    );
};

export default MarketingStudio;
